# Generated by Django 4.2.5 on 2023-09-16 21:39

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribe',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Обязательно для заполнения.', 'invalid': 'Введите корректный E-mail.', 'unique': 'Пользователь с таким e-mail уже существует.'}, max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Некорректный e-mail!')], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(error_messages={'blank': 'Обязательно для заполнения.', 'invalid': 'Введите корректный пароль.'}, max_length=150, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'Обязательно для заполнения.', 'invalid': 'Введите корректный username.', 'unique': 'Пользователь с таким username уже существует.'}, max_length=150, unique=True, validators=[users.validators.validate_username], verbose_name='Username'),
        ),
    ]
